<a href="https://colab.research.google.com/github/ShilpaVasista/PDA---23CSE313/blob/main/ravel.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a = np.arange(1,10).reshape((3,3))
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
flattened = a.ravel()
print(flattened)

[1 2 3 4 5 6 7 8 9]


In [ ]:
flattened[2] = 10
print(a)

[[ 1  2 10]
 [ 4  5  6]
 [ 7  8  9]]


In [ ]:
a.flags['C_CONTIGUOUS']

True

In [ ]:
np.ravel(a,order='F')

array([1, 4, 7, 2, 5, 8, 3, 6, 9])

In [ ]:
b = np.arange(9).reshape([3,3])
print(b)
non_contiguous = b[:,::2]
print(non_contiguous)
print(non_contiguous.flags['C_CONTIGUOUS'])
print(b)
flattened = non_contiguous.ravel()
print(b)
flattened[0] = 100
print(b)
print("flattened")
print(flattened)

print()
print("Original Array")
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 2]
 [3 5]
 [6 8]]
False
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
flattened
[100   2   3   5   6   8]

Original Array
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
non_contiguous = b[:,::2]
print(non_contiguous)

[[0 2]
 [3 5]
 [6 8]]


In [ ]:
print(non_contiguous.flags['C_CONTIGUOUS'])
print(b)

False
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
non_contiguous.ravel()
print(b)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
non_contiguous[0] = 100
print(b)

[[100   1 100]
 [  3   4   5]
 [  6   7   8]]


In [ ]:
print("non_contiguous")
print(non_contiguous)

print()
print("Original Array")
print(b)

non_contiguous
[[100 100]
 [  3   5]
 [  6   8]]

Original Array
[[100   1 100]
 [  3   4   5]
 [  6   7   8]]


In [ ]:
import numpy as np

# Create a 2D contiguous array
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Check contiguity
print("Is the original array C-contiguous?", arr.flags['C_CONTIGUOUS'])

# Ravel the contiguous array
flattened = arr.ravel()
print("Flattened Array (contiguous):", flattened)

# Modify the flattened array
flattened[0] = 99
print("Modified Original Array (view expected):")
print(arr)

# Create a non-contiguous array by slicing
non_contiguous = arr[:, ::2]  # Select every 2nd column
print("\nNon-Contiguous Array:")
print(non_contiguous)

# Check contiguity
print("Is the sliced array C-contiguous?", non_contiguous.flags['C_CONTIGUOUS'])

# Ravel the non-contiguous array
flattened_non_contiguous = non_contiguous.ravel()
print("\nFlattened Non-Contiguous Array:", flattened_non_contiguous)

# Modify the flattened array
flattened_non_contiguous[0] = 88
print("Modified Non-Contiguous Array:")
print(non_contiguous)  # No change expected
print("flattened_non_contiguous")
print(flattened_non_contiguous)
print("original")
print(arr)


Is the original array C-contiguous? True
Flattened Array (contiguous): [1 2 3 4 5 6]
Modified Original Array (view expected):
[[99  2  3]
 [ 4  5  6]]

Non-Contiguous Array:
[[99  3]
 [ 4  6]]
Is the sliced array C-contiguous? False

Flattened Non-Contiguous Array: [99  3  4  6]
Modified Non-Contiguous Array:
[[99  3]
 [ 4  6]]
flattened_non_contiguous
[88  3  4  6]
original
[[99  2  3]
 [ 4  5  6]]


In [ ]:
import numpy as np

# Create a 2D contiguous array
arr = np.arange(9).reshape((3,3))

# Check contiguity
print("Is the original array C-contiguous?", arr.flags['C_CONTIGUOUS'])

# Ravel the contiguous array
flattened = arr.ravel()
print("Flattened Array (contiguous):", flattened)

# Modify the flattened array
flattened[0] = 99
print("Modified Original Array (view expected):")
print(arr)

# Create a non-contiguous array by slicing
non_contiguous = arr[:, ::2]  # Select every 2nd column
print("\nNon-Contiguous Array:")
print(non_contiguous)

# Check contiguity
print("Is the sliced array C-contiguous?", non_contiguous.flags['C_CONTIGUOUS'])

# Ravel the non-contiguous array
flattened_non_contiguous = non_contiguous.ravel()
print("\nFlattened Non-Contiguous Array:", flattened_non_contiguous)

# Modify the flattened array
flattened_non_contiguous[0] = 88
print("Modified Non-Contiguous Array:")
print(non_contiguous)  # No change expected
print("flattened_non_contiguous")
print(flattened_non_contiguous)
print("original")
print(arr)


Is the original array C-contiguous? True
Flattened Array (contiguous): [0 1 2 3 4 5 6 7 8]
Modified Original Array (view expected):
[[99  1  2]
 [ 3  4  5]
 [ 6  7  8]]

Non-Contiguous Array:
[[99  2]
 [ 3  5]
 [ 6  8]]
Is the sliced array C-contiguous? False

Flattened Non-Contiguous Array: [99  2  3  5  6  8]
Modified Non-Contiguous Array:
[[99  2]
 [ 3  5]
 [ 6  8]]
flattened_non_contiguous
[88  2  3  5  6  8]
original
[[99  1  2]
 [ 3  4  5]
 [ 6  7  8]]


In [ ]:
import numpy as np
a=np.arange(9).reshape((3,3))
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
a.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
a.flags['C_CONTIGUOUS']

True

In [ ]:
a_flat = a.ravel()
a_flat[0] = 100
print("a_flat")
print(a_flat)
print("a")
print(a)

a_flat
[100   1   2   3   4   5   6   7   8]
a
[[100   1   2]
 [  3   4   5]
 [  6   7   8]]


In [ ]:
b = np.zeros((3,3))
print(b)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
b_slice = b[:,::2]
print(b_slice)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [ ]:
b_slice_flat = b_slice.ravel()
print(b_slice_flat)

[0. 0. 0. 0. 0. 0.]


In [ ]:
b_slice_flat[0] = 100
print("b_slice_flat")
print(b_slice_flat)
print("original")
print(b)
print("b_slice")
print(b_slice)
print("Is b Contiguous", b.flags['C_CONTIGUOUS'])
print("Is b_slice Contiguous", b_slice.flags['C_CONTIGUOUS'])
print("Is b_slice_flat Contiguous", b_slice_flat.flags['C_CONTIGUOUS'])


b_slice_flat
[100.   0.   0.   0.   0.   0.]
original
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
b_slice
[[0. 0.]
 [0. 0.]
 [0. 0.]]
Is b Contiguous True
Is b_slice Contiguous False
Is b_slice_flat Contiguous True


In [ ]:
a = np.zeros((3,3))
print("a")
print(a)
b = np.ones((3,3))
print("b")
print(b)
result = np.vstack((a,b))
print("result")
print(result)

a
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
b
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
result
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
result_hstack = np.hstack((a,b))
print(result_hstack)

[[0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1.]]


In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])
result = np.column_stack([a,b,c])
print(result)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [ ]:
result_row = np.row_stack([a,b,c])
print(result_row)

NameError: name 'a' is not defined

In [ ]:
import numpy as np
A = np.arange(16).reshape((4, 4))
print(A)
print()
[B, C] = np.hsplit(A, 2)
print(B)
print()
print(C)
print()

[D, E] = np.vsplit(A, 2)
print(D)
print()
print(E)
print()

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]

[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]

[[0 1 2 3]
 [4 5 6 7]]

[[ 8  9 10 11]
 [12 13 14 15]]



In [ ]:
A = np.arange(16).reshape((4, 4))
print(A)
[A1, A2, A3] = np.split(A, [1, 3], axis=1)
print(A1)
print(A2)
print(A3)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0]
 [ 4]
 [ 8]
 [12]]
[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]]
[[ 3]
 [ 7]
 [11]
 [15]]


In [ ]:
A = np.arange(16).reshape(4, 4)

B = np.arange(4)
A + B


array([[ 0,  2,  4,  6],
       [ 4,  6,  8, 10],
       [ 8, 10, 12, 14],
       [12, 14, 16, 18]])

In [ ]:
m = np.arange(6).reshape(3, 1, 2)
print(m)
print()
n = np.arange(6).reshape(3, 2, 1)
print(n)
print()
m + n


[[[0 1]]

 [[2 3]]

 [[4 5]]]

[[[0]
  [1]]

 [[2]
  [3]]

 [[4]
  [5]]]



array([[[ 0,  1],
        [ 1,  2]],

       [[ 4,  5],
        [ 5,  6]],

       [[ 8,  9],
        [ 9, 10]]])

In [ ]:
import numpy as np

def create_array(m, n):
    """Create an m x n integer array."""
    return np.zeros((m, n), dtype=int)

def fill_with_value(array, value):
    """Fill the array with a specific value."""
    array.fill(value)

def randomly_generate_numbers(array, low, high):
    """Populate the array with random integers within the specified range [low, high)."""
    array[:] = np.random.randint(low, high, size=array.shape)

def main():
    # Dimensions of the array
    m, n = 4, 5  # Example dimensions (can be modified or taken as input)

    # Create an m x n array
    my_array = create_array(m, n)

    # Print initial array shape and total elements
    print(f"Initial Shape of the array: {my_array.shape}")
    print(f"Total number of elements: {my_array.size}")

    # Fill the array with a specific value
    fill_with_value(my_array, 10)
    print("\nArray after filling with the value 10:")
    print(my_array)

    # Populate the array with random integers in a range
    randomly_generate_numbers(my_array, 1, 100)
    print("\nArray after populating with random numbers (range 1-100):")
    print(my_array)

# Run the program
if __name__ == "__main__":
    main()


Initial Shape of the array: (4, 5)
Total number of elements: 20

Array after filling with the value 10:
[[10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]]

Array after populating with random numbers (range 1-100):
[[96 14 86 57 22]
 [52 89 27 76 59]
 [15 76  9  4 59]
 [97 54  6 20 91]]
